In [1]:
!pip install mlflow

Requirement already satisfied: mlflow in c:\users\t ganesh\anaconda3\lib\site-packages (3.11.1)
Requirement already satisfied: mlflow-skinny==3.11.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (3.11.1)
Requirement already satisfied: mlflow-tracing==3.11.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (3.11.1)
Requirement already satisfied: Flask-CORS<7 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (5.0.0)
Requirement already satisfied: Flask<4 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (3.0.3)
Requirement already satisfied: aiohttp<4 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (3.11.10)
Requirement already satisfied: alembic!=1.10.0,<2 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (1.16.2)
Requirement already satisfied: cryptography<47,>=43.0.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (44.0.1)
Requirement already satisfied: docker<8,>=4.0.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (7.1.0)
Requirement already satisfied: graphene<4 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (3.4.3)
Requirement already satisfied: huey<3,>=2.5.4 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (2.6.0)
Requirement already satisfied: matplotlib<4 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (2.2.6)
Requirement already satisfied: pandas<3 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (2.3.3)
Requirement already satisfied: pyarrow<24,>=4.0.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (21.0.0)
Requirement already satisfied: scikit-learn<2 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (1.6.0)
Requirement already satisfied: scipy<2 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (1.16.3)
Requirement already satisfied: skops<1 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (2.0.39)
Requirement already satisfied: waitress<4 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (3.0.2)
Requirement already satisfied: cachetools<8,>=5.0.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (8.3.1)
Requirement already satisfied: cloudpickle<4 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (3.0.0)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (0.105.0)
Requirement already satisfied: fastapi<1 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (0.128.0)
Requirement already satisfied: gitpython<4,>=3.1.9 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (3.1.43)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (8.5.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (1.39.1)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (1.39.1)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (1.39.1)
Requirement already satisfied: packaging<27 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (25.0)
Requirement already satisfied: protobuf<8,>=3.12.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (6.33.2)
Requirement already satisfied: pydantic<3,>=2.0.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (2.12.5)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (1.0.0)
Requirement already satisfied: pyyaml<7,>=5.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (6.0.2)
Requirement already satisfied: requests<3,>=2.17.3 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (2.32.5)
Requirement already satisfied: sqlparse<1,>=0.4.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (0.5.5)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (0.40.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\t ganesh\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\t ganesh\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (1.22.0)
Requirement already satisfied: Mako in c:\users\t ganesh\anaconda3\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (1.2.3)
Requirement already satisfied: colorama in c:\users\t ganesh\anaconda3\lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.11.1->mlflow) (0.4.6)
Requirement already satisfied: cffi>=1.12 in c:\users\t ganesh\anaconda3\lib\site-packages (from cryptography<47,>=43.0.0->mlflow) (1.17.1)
Requirement already satisfied: google-auth~=2.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (2.48.0)
Requirement already satisfied: pywin32>=304 in c:\users\t ganesh\anaconda3\lib\site-packages (from docker<8,>=4.0.0->mlflow) (308)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from docker<8,>=4.0.0->mlflow) (2.3.0)
Requirement already satisfied: starlette<0.51.0,>=0.40.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.50.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\t ganesh\anaconda3\lib\site-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.0.4)
Requirement already satisfied: Werkzeug>=3.0.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\t ganesh\anaconda3\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\t ganesh\anaconda3\lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: blinker>=1.6.2 in c:\users\t ganesh\anaconda3\lib\site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.11.1->mlflow) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.11.1->mlflow) (4.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\t ganesh\anaconda3\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (4.9.1)
Requirement already satisfied: graphql-core<3.3,>=3.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from graphene<4->mlflow) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: zipp>=3.20 in c:\users\t ganesh\anaconda3\lib\site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.11.1->mlflow) (3.21.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\t ganesh\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (1.4.8)
Requirement already satisfied: pillow>=8 in c:\users\t ganesh\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (3.2.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.60b1 in c:\users\t ganesh\anaconda3\lib\site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.11.1->mlflow) (0.60b1)
Requirement already satisfied: pytz>=2020.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from pandas<3->mlflow) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\t ganesh\anaconda3\lib\site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.11.1->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\t ganesh\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.11.1->mlflow) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\t ganesh\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.11.1->mlflow) (0.4.2)
Requirement already satisfied: six>=1.5 in c:\users\t ganesh\anaconda3\lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\t ganesh\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\t ganesh\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\t ganesh\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (2026.1.4)
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\t ganesh\anaconda3\lib\site-packages (from rsa<5,>=3.1.4->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (0.4.8)
Requirement already satisfied: joblib>=1.2.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from scikit-learn<2->mlflow) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in c:\users\t ganesh\anaconda3\lib\site-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\t ganesh\anaconda3\lib\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.1.1)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\t ganesh\anaconda3\lib\site-packages (from starlette<0.51.0,>=0.40.0->fastapi<1->mlflow-skinny==3.11.1->mlflow) (4.12.0)
Requirement already satisfied: h11>=0.8 in c:\users\t ganesh\anaconda3\lib\site-packages (from uvicorn<1->mlflow-skinny==3.11.1->mlflow) (0.16.0)
Requirement already satisfied: pycparser in c:\users\t ganesh\anaconda3\lib\site-packages (from cffi>=1.12->cryptography<47,>=43.0.0->mlflow) (2.21)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from Jinja2>=3.1.2->Flask<4->mlflow) (3.0.2)
Requirement already satisfied: wcwidth in c:\users\t ganesh\anaconda3\lib\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.2.5)

In [2]:
!pip install mlflow dagshub

Requirement already satisfied: mlflow in c:\users\t ganesh\anaconda3\lib\site-packages (3.11.1)
Requirement already satisfied: dagshub in c:\users\t ganesh\anaconda3\lib\site-packages (0.7.0)
Requirement already satisfied: mlflow-skinny==3.11.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (3.11.1)
Requirement already satisfied: mlflow-tracing==3.11.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (3.11.1)
Requirement already satisfied: Flask-CORS<7 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (5.0.0)
Requirement already satisfied: Flask<4 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (3.0.3)
Requirement already satisfied: aiohttp<4 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (3.11.10)
Requirement already satisfied: alembic!=1.10.0,<2 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (1.16.2)
Requirement already satisfied: cryptography<47,>=43.0.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (44.0.1)
Requirement already satisfied: docker<8,>=4.0.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (7.1.0)
Requirement already satisfied: graphene<4 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (3.4.3)
Requirement already satisfied: huey<3,>=2.5.4 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (2.6.0)
Requirement already satisfied: matplotlib<4 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (3.10.0)
Requirement already satisfied: numpy<3 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (2.2.6)
Requirement already satisfied: pandas<3 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (2.3.3)
Requirement already satisfied: pyarrow<24,>=4.0.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (21.0.0)
Requirement already satisfied: scikit-learn<2 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (1.6.0)
Requirement already satisfied: scipy<2 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (1.16.3)
Requirement already satisfied: skops<1 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (0.14.0)
Requirement already satisfied: sqlalchemy<3,>=1.4.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (2.0.39)
Requirement already satisfied: waitress<4 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow) (3.0.2)
Requirement already satisfied: cachetools<8,>=5.0.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (5.5.1)
Requirement already satisfied: click<9,>=7.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (8.3.1)
Requirement already satisfied: cloudpickle<4 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (3.0.0)
Requirement already satisfied: databricks-sdk<1,>=0.20.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (0.105.0)
Requirement already satisfied: fastapi<1 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (0.128.0)
Requirement already satisfied: gitpython<4,>=3.1.9 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (3.1.43)
Requirement already satisfied: importlib_metadata!=4.7.0,<9,>=3.7.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (8.5.0)
Requirement already satisfied: opentelemetry-api<3,>=1.9.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (1.39.1)
Requirement already satisfied: opentelemetry-proto<3,>=1.9.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (1.39.1)
Requirement already satisfied: opentelemetry-sdk<3,>=1.9.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (1.39.1)
Requirement already satisfied: packaging<27 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (25.0)
Requirement already satisfied: protobuf<8,>=3.12.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (6.33.2)
Requirement already satisfied: pydantic<3,>=2.0.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (2.12.5)
Requirement already satisfied: python-dotenv<2,>=0.19.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (1.0.0)
Requirement already satisfied: pyyaml<7,>=5.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (6.0.2)
Requirement already satisfied: requests<3,>=2.17.3 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (2.32.5)
Requirement already satisfied: sqlparse<1,>=0.4.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (0.5.5)
Requirement already satisfied: typing-extensions<5,>=4.0.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (4.15.0)
Requirement already satisfied: uvicorn<1 in c:\users\t ganesh\anaconda3\lib\site-packages (from mlflow-skinny==3.11.1->mlflow) (0.40.0)
Requirement already satisfied: aiohappyeyeballs>=2.3.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (2.4.4)
Requirement already satisfied: aiosignal>=1.1.2 in c:\users\t ganesh\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (1.2.0)
Requirement already satisfied: attrs>=17.3.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (25.4.0)
Requirement already satisfied: frozenlist>=1.1.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (1.5.0)
Requirement already satisfied: multidict<7.0,>=4.5 in c:\users\t ganesh\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (6.1.0)
Requirement already satisfied: propcache>=0.2.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (0.3.1)
Requirement already satisfied: yarl<2.0,>=1.17.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from aiohttp<4->mlflow) (1.22.0)
Requirement already satisfied: Mako in c:\users\t ganesh\anaconda3\lib\site-packages (from alembic!=1.10.0,<2->mlflow) (1.2.3)
Requirement already satisfied: colorama in c:\users\t ganesh\anaconda3\lib\site-packages (from click<9,>=7.0->mlflow-skinny==3.11.1->mlflow) (0.4.6)
Requirement already satisfied: cffi>=1.12 in c:\users\t ganesh\anaconda3\lib\site-packages (from cryptography<47,>=43.0.0->mlflow) (1.17.1)
Requirement already satisfied: google-auth~=2.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (2.48.0)
Requirement already satisfied: pywin32>=304 in c:\users\t ganesh\anaconda3\lib\site-packages (from docker<8,>=4.0.0->mlflow) (308)
Requirement already satisfied: urllib3>=1.26.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from docker<8,>=4.0.0->mlflow) (2.3.0)
Requirement already satisfied: starlette<0.51.0,>=0.40.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.50.0)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\t ganesh\anaconda3\lib\site-packages (from fastapi<1->mlflow-skinny==3.11.1->mlflow) (0.0.4)
Requirement already satisfied: Werkzeug>=3.0.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: Jinja2>=3.1.2 in c:\users\t ganesh\anaconda3\lib\site-packages (from Flask<4->mlflow) (3.1.6)
Requirement already satisfied: itsdangerous>=2.1.2 in c:\users\t ganesh\anaconda3\lib\site-packages (from Flask<4->mlflow) (2.2.0)
Requirement already satisfied: blinker>=1.6.2 in c:\users\t ganesh\anaconda3\lib\site-packages (from Flask<4->mlflow) (1.9.0)
Requirement already satisfied: gitdb<5,>=4.0.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from gitpython<4,>=3.1.9->mlflow-skinny==3.11.1->mlflow) (4.0.7)
Requirement already satisfied: smmap<5,>=3.0.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from gitdb<5,>=4.0.1->gitpython<4,>=3.1.9->mlflow-skinny==3.11.1->mlflow) (4.0.0)
Requirement already satisfied: pyasn1-modules>=0.2.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (0.2.8)
Requirement already satisfied: rsa<5,>=3.1.4 in c:\users\t ganesh\anaconda3\lib\site-packages (from google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (4.9.1)
Requirement already satisfied: graphql-core<3.3,>=3.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from graphene<4->mlflow) (3.2.8)
Requirement already satisfied: graphql-relay<3.3,>=3.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from graphene<4->mlflow) (3.2.0)
Requirement already satisfied: python-dateutil<3,>=2.7.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from graphene<4->mlflow) (2.9.0.post0)
Requirement already satisfied: zipp>=3.20 in c:\users\t ganesh\anaconda3\lib\site-packages (from importlib_metadata!=4.7.0,<9,>=3.7.0->mlflow-skinny==3.11.1->mlflow) (3.21.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (1.3.1)
Requirement already satisfied: cycler>=0.10 in c:\users\t ganesh\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (4.55.3)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (1.4.8)
Requirement already satisfied: pillow>=8 in c:\users\t ganesh\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (11.1.0)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from matplotlib<4->mlflow) (3.2.0)
Requirement already satisfied: opentelemetry-semantic-conventions==0.60b1 in c:\users\t ganesh\anaconda3\lib\site-packages (from opentelemetry-sdk<3,>=1.9.0->mlflow-skinny==3.11.1->mlflow) (0.60b1)
Requirement already satisfied: pytz>=2020.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from pandas<3->mlflow) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\t ganesh\anaconda3\lib\site-packages (from pandas<3->mlflow) (2025.2)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.11.1->mlflow) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\t ganesh\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.11.1->mlflow) (2.41.5)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\t ganesh\anaconda3\lib\site-packages (from pydantic<3,>=2.0.0->mlflow-skinny==3.11.1->mlflow) (0.4.2)
Requirement already satisfied: six>=1.5 in c:\users\t ganesh\anaconda3\lib\site-packages (from python-dateutil<3,>=2.7.0->graphene<4->mlflow) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\t ganesh\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\t ganesh\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (3.11)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\t ganesh\anaconda3\lib\site-packages (from requests<3,>=2.17.3->mlflow-skinny==3.11.1->mlflow) (2026.1.4)
Requirement already satisfied: pyasn1>=0.1.3 in c:\users\t ganesh\anaconda3\lib\site-packages (from rsa<5,>=3.1.4->google-auth~=2.0->databricks-sdk<1,>=0.20.0->mlflow-skinny==3.11.1->mlflow) (0.4.8)
Requirement already satisfied: joblib>=1.2.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from scikit-learn<2->mlflow) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from scikit-learn<2->mlflow) (3.6.0)
Requirement already satisfied: prettytable>=3.9 in c:\users\t ganesh\anaconda3\lib\site-packages (from skops<1->mlflow) (3.17.0)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\t ganesh\anaconda3\lib\site-packages (from sqlalchemy<3,>=1.4.0->mlflow) (3.1.1)
Requirement already satisfied: anyio<5,>=3.6.2 in c:\users\t ganesh\anaconda3\lib\site-packages (from starlette<0.51.0,>=0.40.0->fastapi<1->mlflow-skinny==3.11.1->mlflow) (4.12.0)
Requirement already satisfied: h11>=0.8 in c:\users\t ganesh\anaconda3\lib\site-packages (from uvicorn<1->mlflow-skinny==3.11.1->mlflow) (0.16.0)
Requirement already satisfied: appdirs>=1.4.4 in c:\users\t ganesh\anaconda3\lib\site-packages (from dagshub) (1.4.4)
Requirement already satisfied: httpx>=0.23.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from dagshub) (0.27.2)
Requirement already satisfied: rich>=13.1.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from dagshub) (15.0.0)
Requirement already satisfied: dacite~=1.6.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from dagshub) (1.6.0)
Requirement already satisfied: tenacity>=8.2.2 in c:\users\t ganesh\anaconda3\lib\site-packages (from dagshub) (9.0.0)
Requirement already satisfied: gql[requests] in c:\users\t ganesh\anaconda3\lib\site-packages (from dagshub) (4.0.0)
Requirement already satisfied: dataclasses-json in c:\users\t ganesh\anaconda3\lib\site-packages (from dagshub) (0.6.7)
Requirement already satisfied: treelib>=1.6.4 in c:\users\t ganesh\anaconda3\lib\site-packages (from dagshub) (1.8.0)
Requirement already satisfied: pathvalidate>=3.0.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from dagshub) (3.3.1)
Requirement already satisfied: boto3 in c:\users\t ganesh\anaconda3\lib\site-packages (from dagshub) (1.42.95)
Requirement already satisfied: semver in c:\users\t ganesh\anaconda3\lib\site-packages (from dagshub) (3.0.2)
Requirement already satisfied: dagshub-annotation-converter>=0.2.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from dagshub) (0.2.0)
Requirement already satisfied: pycparser in c:\users\t ganesh\anaconda3\lib\site-packages (from cffi>=1.12->cryptography<47,>=43.0.0->mlflow) (2.21)
Requirement already satisfied: lxml in c:\users\t ganesh\anaconda3\lib\site-packages (from dagshub-annotation-converter>=0.2.0->dagshub) (5.3.0)
Requirement already satisfied: httpcore==1.* in c:\users\t ganesh\anaconda3\lib\site-packages (from httpx>=0.23.0->dagshub) (1.0.9)
Requirement already satisfied: sniffio in c:\users\t ganesh\anaconda3\lib\site-packages (from httpx>=0.23.0->dagshub) (1.3.1)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from Jinja2>=3.1.2->Flask<4->mlflow) (3.0.2)
Requirement already satisfied: wcwidth in c:\users\t ganesh\anaconda3\lib\site-packages (from prettytable>=3.9->skops<1->mlflow) (0.2.5)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from rich>=13.1.0->dagshub) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from rich>=13.1.0->dagshub) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich>=13.1.0->dagshub) (0.1.0)
Requirement already satisfied: botocore<1.43.0,>=1.42.95 in c:\users\t ganesh\anaconda3\lib\site-packages (from boto3->dagshub) (1.42.95)
Requirement already satisfied: jmespath<2.0.0,>=0.7.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from boto3->dagshub) (1.0.1)
Requirement already satisfied: s3transfer<0.17.0,>=0.16.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from boto3->dagshub) (0.16.1)
Requirement already satisfied: marshmallow<4.0.0,>=3.18.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from dataclasses-json->dagshub) (3.26.2)
Requirement already satisfied: typing-inspect<1,>=0.4.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from dataclasses-json->dagshub) (0.9.0)
Requirement already satisfied: mypy-extensions>=0.3.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from typing-inspect<1,>=0.4.0->dataclasses-json->dagshub) (1.0.0)
Requirement already satisfied: backoff<3.0,>=1.11.1 in c:\users\t ganesh\anaconda3\lib\site-packages (from gql[requests]->dagshub) (2.2.1)
Requirement already satisfied: requests_toolbelt<2,>=1.0.0 in c:\users\t ganesh\anaconda3\lib\site-packages (from gql[requests]->dagshub) (1.0.0)

In [5]:
#creating baseline model

import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv('../data/interim/train_processed.csv')
df.head()

                                       clean_comment  category
0                         found young modi guess one         1
1  holy shit heard whole johnny gosch story earli...         0
2  porra tava amando ler isso poderia pelo menos ...         0
3         mmw something witty add thread diwali 2016         1
4  similar chart call quality would love see low ...         0

In [7]:
df.dropna(inplace=True)

In [8]:
df.drop_duplicates(inplace=True)

In [9]:
df = df[~(df['clean_comment'].str.strip() == '')]

In [10]:
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [11]:
# Ensure necessary NLTK data is downloaded
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package stopwords to C:\Users\T
[nltk_data]     Ganesh\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to C:\Users\T
[nltk_data]     Ganesh\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

True

In [14]:
# Define the preprocessing function
def preprocess_comment(comment):
    # Convert to lowercase
    comment = comment.lower()

    # Remove trailing and leading whitespaces
    comment = comment.strip()

    # Remove newline characters
    comment = re.sub(r'\n', ' ', comment) 

    # Remove non-alphanumeric characters, except punctuation
    comment = re.sub(r'[^A-Za-z0-9\s!?.,]', '', comment)

    # Remove stopwords but retain important ones for sentiment analysis
    stop_words = set(stopwords.words('english')) - {'not', 'but', 'however', 'no', 'yet'}
    comment = ' '.join([word for word in comment.split() if word not in stop_words])

    # Lemmatize the words
    lemmatizer = WordNetLemmatizer()
    comment = ' '.join([lemmatizer.lemmatize(word) for word in comment.split()])

    return comment

In [13]:
# Apply the preprocessing function to the 'clean_comment' column
df['clean_comment'] = df['clean_comment'].apply(preprocess_comment)

In [15]:
df.head()

                                       clean_comment  category
0                         found young modi guess one         1
1  holy shit heard whole johnny gosch story earli...         0
2  porra tava amando ler isso poderia pelo menos ...         0
3         mmw something witty add thread diwali 2016         1
4  similar chart call quality would love see low ...         0

In [16]:

from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split, cross_val_predict, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [17]:
# Step 1: Vectorize the comments using Bag of Words (CountVectorizer)
vectorizer = CountVectorizer(max_features=10000)  # Bag of Words model with a limit of 1000 features

In [18]:
X = vectorizer.fit_transform(df['clean_comment']).toarray()
y = df['category']  # Assuming 'sentiment' is the target variable (0 or 1 for binary classification)

In [19]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(29042, 10000))

In [20]:
X.shape

(29042, 10000)

In [21]:
y

0        1
1        0
2        0
3        1
4        0
        ..
29429   -1
29430    1
29431    0
29432    1
29433    0
Name: category, Length: 29042, dtype: int64

In [22]:
y.shape

(29042,)

Initialized MLflow to track repo "Ganesh-gsg-45/youtube_sentiment_analyze"

Repository Ganesh-gsg-45/youtube_sentiment_analyze initialized!

MlflowException: API request to endpoint /api/2.0/mlflow/experiments/get-by-name failed with error code 404 != 200. Response body: 'Not Found'

MlflowException: API request to endpoint /api/2.0/mlflow/runs/create failed with error code 422 != 200. Response body: '<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-type" content="text/html; charset=utf-8">
    <meta http-equiv="Content-Security-Policy" content="default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'">
    <meta content="origin" name="referrer">
    <title>Oh no &middot; GitHub</title>
    <meta name="viewport" content="width=device-width">
    <style type="text/css" media="screen">
      body {
        background-color: #f6f8fa;
        color: #24292e;
        font-family: -apple-system,BlinkMacSystemFont,Segoe UI,Helvetica,Arial,sans-serif,Apple Color Emoji,Segoe UI Emoji,Segoe UI Symbol;
        font-size: 14px;
        line-height: 1.5;
        margin: 0;
      }

      .container { margin: 50px auto; max-width: 600px; text-align: center; padding: 0 24px; }

      a { color: #4183c4; text-decoration: none; }
      a:hover { text-decoration: underline; }

      h1 { letter-spacing: -1px; line-height: 60px; font-size: 60px; font-weight: 100; margin: 0px; text-shadow: 0 1px 0 #fff; }
      p { color: rgba(0, 0, 0, 0.5); margin: 20px 0 40px; }

      ul { list-style: none; margin: 25px 0; padding: 0; }
      li { display: table-cell; font-weight: bold; width: 1%; }

      .logo { display: inline-block; margin-top: 35px; }
      .logo-img-2x { display: none; }
      @media
      only screen and (-webkit-min-device-pixel-ratio: 2),
      only screen and (   min--moz-device-pixel-ratio: 2),
      only screen and (     -o-min-device-pixel-ratio: 2/1),
      only screen and (        min-device-pixel-ratio: 2),
      only screen and (                min-resolution: 192dpi),
      only screen and (                min-resolution: 2dppx) {
        .logo-img-1x { display: none; }
        .logo-img-2x { display: inline-block; }
      }

      #suggestions {
        margin-top: 35px;
        color: #ccc;
      }
      #suggestions a {
        color: #666666;
        font-weight: 200;
        font-size: 14px;
        margin: 0 10px;
      }

    </style>
  </head>
  <body>

    <div class="container">

      <h1>What&#8253;</h1>
      <p>Your browser did something unexpected. Please try again. If the error continues,
        try disabling all browser extensions.
      </p>
      <p>Please contact us if the problem persists.</p>
      <div id="suggestions">
        <a href="https://support.github.com/contact">Contact Support</a> &mdash;
        <a href="https://githubstatus.com">GitHub Status</a> &mdash;
        <a href="https://x.com/githubstatus">@githubstatus</a>
      </div>

      <a href="/" class="logo logo-img-1x">
        <img width="32" height="32" title="" alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyRpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoTWFjaW50b3NoKSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDpFMTZCRDY3REIzRjAxMUUyQUQzREIxQzRENUFFNUM5NiIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDpFMTZCRDY3RUIzRjAxMUUyQUQzREIxQzRENUFFNUM5NiI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOkUxNkJENjdCQjNGMDExRTJBRDNEQjFDNEQ1QUU1Qzk2IiBzdFJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOkUxNkJENjdDQjNGMDExRTJBRDNEQjFDNEQ1QUU1Qzk2Ii8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+SM9MCAAAA+5JREFUeNrEV11Ik1EY3s4+ddOp29Q5b0opCgKFsoKoi5Kg6CIhuwi6zLJLoYLopq4qsKKgi4i6CYIoU/q5iDAKs6syoS76IRWtyJ+p7cdt7sf1PGOD+e0c3dygAx/67ZzzPM95/877GYdHRg3ZjMXFxepQKNS6sLCwJxqNNuFpiMfjVs4ZjUa/pmmjeD6VlJS8NpvNT4QQ7mxwjSsJiEQim/1+/9lgMHgIr5ohuxG1WCw9Vqv1clFR0dCqBODElV6v90ogEDjGdYbVjXhpaendioqK07CIR7ZAqE49PT09BPL2PMgTByQGsYiZlQD4uMXtdr+JxWINhgINYhGT2MsKgMrm2dnZXgRXhaHAg5jEJodUAHxux4LudHJE9RdEdA+i3Juz7bGHe4mhE9FNrgwBCLirMFV9Okh5eflFh8PR5nK5nDabrR2BNJlKO0T35+Li4n4+/J+/JQCxhmu5h3uJoXNHPbmWZAHMshWB8l5/ipqammaAf0zPDDx1ONV3vurdidqwAQL+pEc8sLcAe1CCvQ3YHxIW8Pl85xSWNC1hADDIv0rIE/o4J0k3kww4xSlwIhcq3EFFOm7KN/hUGOQkt0CFa5WpNJlMvxBEz/IVQAxg/ZRZl9wiHA63yDYieM7DnLP5CiAGsC7I5sgtYKJGWe2A8seFqgFJrJjEPY1Cn3pJ8/9W1e5VWsFDTEmFrBcoDhZJEQkXuhICMyKpjhahqN21hRYATKfUOlDmkygrR4o4C0VOLGJKrOITKB4jijzdXygBKixyC5TDQdnk/Pz8qRw6oOWGlsTKGOQW6OH6FBWsyePxdOXLTgxiyebILZCjz+GLgMIKnXNzc49YMlcRdHXcSwxFVgTInQhC9G33UhNoJLuqq6t345p9y3eUy8OTk5PjAHuI9uo4b07FBaOhsu0A4Unc+T1TU1Nj3KsSSE5yJ65jqF2DDd8QqWYmAZrIM2VlZTdnZmb6AbpdV9V6ec9znf5Q7HjYumdRE0JOp3MjitO4SFa+cZz8Umqe3TCbSLvdfkR/kWDdNQl5InuTcysOcpFT35ZrbBxx4p3JAHlZVVW1D/634VRt+FvLBgK/v5LV9WS+10xMTEwtRw7XvqOL+e2Q8V3AYIOIAXQ26/heWVnZCVfcyKHg2CBgTpmPmjYM8l24GyaUHyaIh7XwfR9ErE8qHoDfn2LTNAVC0HX6MFcBIP8Bi+6F6cdW/DICkANRfx99fEYFQ7Nph5i/uQiA214gno7K+guhaiKg9gC62+M8eR7XsBsYJ4ilam60Fb7r7uAj8wFyuwM1oIOWgfmDy6RXEEQzJMPe23DXrVS7rtyD3Df8z/FPgAEAzWU5Ku59ZAUAAAAASUVORK5CYII=">
      </a>

      <a href="/" class="logo logo-img-2x">
        <img width="32" height="32" title="" alt="" src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAGXRFWHRTb2Z0d2FyZQBBZG9iZSBJbWFnZVJlYWR5ccllPAAAAyRpVFh0WE1MOmNvbS5hZG9iZS54bXAAAAAAADw/eHBhY2tldCBiZWdpbj0i77u/IiBpZD0iVzVNME1wQ2VoaUh6cmVTek5UY3prYzlkIj8+IDx4OnhtcG1ldGEgeG1sbnM6eD0iYWRvYmU6bnM6bWV0YS8iIHg6eG1wdGs9IkFkb2JlIFhNUCBDb3JlIDUuMy1jMDExIDY2LjE0NTY2MSwgMjAxMi8wMi8wNi0xNDo1NjoyNyAgICAgICAgIj4gPHJkZjpSREYgeG1sbnM6cmRmPSJodHRwOi8vd3d3LnczLm9yZy8xOTk5LzAyLzIyLXJkZi1zeW50YXgtbnMjIj4gPHJkZjpEZXNjcmlwdGlvbiByZGY6YWJvdXQ9IiIgeG1sbnM6eG1wPSJodHRwOi8vbnMuYWRvYmUuY29tL3hhcC8xLjAvIiB4bWxuczp4bXBNTT0iaHR0cDovL25zLmFkb2JlLmNvbS94YXAvMS4wL21tLyIgeG1sbnM6c3RSZWY9Imh0dHA6Ly9ucy5hZG9iZS5jb20veGFwLzEuMC9zVHlwZS9SZXNvdXJjZVJlZiMiIHhtcDpDcmVhdG9yVG9vbD0iQWRvYmUgUGhvdG9zaG9wIENTNiAoTWFjaW50b3NoKSIgeG1wTU06SW5zdGFuY2VJRD0ieG1wLmlpZDpEQUM1QkUxRUI0MUMxMUUyQUQzREIxQzRENUFFNUM5NiIgeG1wTU06RG9jdW1lbnRJRD0ieG1wLmRpZDpEQUM1QkUxRkI0MUMxMUUyQUQzREIxQzRENUFFNUM5NiI+IDx4bXBNTTpEZXJpdmVkRnJvbSBzdFJlZjppbnN0YW5jZUlEPSJ4bXAuaWlkOkUxNkJENjdGQjNGMDExRTJBRDNEQjFDNEQ1QUU1Qzk2IiBzdFJlZjpkb2N1bWVudElEPSJ4bXAuZGlkOkUxNkJENjgwQjNGMDExRTJBRDNEQjFDNEQ1QUU1Qzk2Ii8+IDwvcmRmOkRlc2NyaXB0aW9uPiA8L3JkZjpSREY+IDwveDp4bXBtZXRhPiA8P3hwYWNrZXQgZW5kPSJyIj8+hfPRaQAAB6lJREFUeNrsW2mME2UYbodtt+2222u35QheoCCYGBQligIJgkZJNPzgigoaTEj8AdFEMfADfyABkgWiiWcieK4S+QOiHAYUj2hMNKgYlEujpNttu9vttbvdw+chU1K6M535pt3ubHCSyezR+b73eb73+t7vrfXsufOW4bz6+vom9/b23ovnNNw34b5xYGAgODg46Mbt4mesVmsWd1qSpHhdXd2fuP/Afcput5/A88xwymcdBgLqenp6FuRyuWV4zu/v759QyWBjxoz5t76+/gun09mK5xFyakoCAPSaTCazNpvNPoYVbh6O1YKGRF0u13sNDQ27QMzfpiAAKj0lnU6/gBVfAZW2WWpwwVzy0IgP3G73FpjI6REhAGA9qVRqA1b9mVoBVyIC2tDi8Xg24+dUzQiAbS/s7Ox8G2o/3mKCC+Zw0efzPQEfcVjYrARX3dbV1bUtHo8fMgt42f+Mp0yUTVQbdWsAHVsikdiHkHaPxcQXQufXgUBgMRxme9U0AAxfH4vFvjM7eF6UkbJS5qoQwEQGA57Ac5JllFyUVZZ5ckUEgMVxsK2jlSYzI+QXJsiyjzNEAJyJAzb/KQa41jJKL8pODMQiTEAymXw5n8/P0IjD3bh7Rgog59aanxiIRTVvV/oj0tnHca/WMrVwODwB3raTGxzkBg/gnZVapFV62Wy2n5AO70HM/5wbJ0QnXyQSaVPDIuNZzY0V3ntHMwxiwHA0Gj2Np7ecIBDgaDAYXKCQJM1DhrgJ3nhulcPbl8j4NmHe46X/g60fwbz3aewjkqFQaAqebWU1AOqyQwt8Id6qEHMc97zu7u7FGGsn7HAiVuosVw7P35C1nccdgSCxop1dHeZswmfHMnxBo6ZTk+jN8dl/vF7vWofDsa+MLN9oEUBMxOb3+1eoEsBVw6Zmua49r8YmhAKDiEPcMwBsxMiqQ+ixzPFxZyqRpXARG/YOr1ObFJ0gUskXBbamcR1OKmMUvDxHRAu8/LmY3jFLMUpFqz9HxG65smYJdyKyECOxDiEAe/p1gjF2oonivZAsxVgl2daa4EQWCW6J55qFAFFZiJWYLxNQy2qOSUzGRsyXCUDIeliwAHEO4WSlWQBRFoZakXcKmCXmyXAKs0Ve9vl8q42WoIYpJU4hV3hKcNs8m9gl7p/xQ73eF5kB4j5mNrWmTJRNwAzqiV1CxjVTZCIkEq+Z1bZFZSN2CenmVAFVy4Plz8xKAGWjjAKFk6lCBMDR/MJjLLMSQNm43xAiQKTaA+9/wewhDjL+JVI1kkTSSOTcKbMTwPqESAot6dn6Fr1gHwVJju6IRuyiByPuUUBAg5DGkAgBmxlvdgIEK9gDkohdY/BJo4CAG0R8miRSsGABkgVQs4KXu098IgUXSSRsFAoKZiVAVDY2WUiiPTjYRi41KwGisrGsLtlsth8Fiwnz2fBkQvWfRtlE3iF2yW63/yCacXZ1dW02GwGyTFaRd4idJnCKHRaCxYRHoG5LTKT6SyiToP1fJHbmAYPYRR0UnZQtMnA6s0zg+GZBlt0Gdo7EPHgpE3Q6nZ8YyLhc8Xj8MJh/aKTAY+5FPAKHLE7RdwuYJZmNwzyCMkBCYyKROJBMJl9B/PXXCjjmCmDOVzH3fiPpObEWGqoKe4EBl8v1hlqsdLvd23mkxHM9pc9kMpmno9HoeTii7ewbHEZPPx1ztLS1tV3AnGuMjiNjvbQFuHw6zDo5By7dTPAQNBgMLrRarTkSls1mnwT7uwp9virx9QzbW/HuV/j5d/b+6jniKlllP8lkeONJDk+dq9GsQTnC4fB1heO0K47Hwe7WdDr9nAKgXwOBwHI+C45Htj1d6sd429TUNEcmUdc+PRaLHcvn87dXW4ugzdsaGxufL94NFv9zi1J7GVbhlvb2dnaJ3SVrxfc+n2+NTsZ7/H7/Mr3g5XdSIHyJSH1PZ+7fToyl2+ErqilgZ4NaLYB9goVGaHjR93Hv1ZrU4XDsFT20kH3PObzbWk0CgG1jacVIUnAQb9F+VexyLMzkpcLv0IJV7AHQIOCAUYHx7v5qgScmYHtTqSAyZLEJTK22Bie4iq3xsqpm4SAf9Hq9a2DnJ4uLK3SEULcdRvp3i3zHySqpficxEdsQc1NrlYXXvR+O7qASSezXB+h1SuUomgg9LL8BUoV4749EIolKh+EiqWmqVEZlDgHks2pxHw7xTqUQw9J5NcAXOK10AGIoZ6Zli6JY6Z1Q461KoZ4NiKLHarW+KDsxlDUPHZ5zPQZqUVDPJsTqb5n9malbpAh8C2XXDLl62+WZIDFRUlNVOiwencnNU3aQEkL+cDMSoLvZo2fQB7AJssNAuFuvorlDVVkkg2I87+jo2K2QAVphDrfyViK5VqtO34OkaxXCp+7drdDBCAdubm6eidX+2WwqT5komwh4YQLk+H4aE93h8Xg2gvHekQZOGSgLZTLyDTLJ4Lx9/KZWKBSainT4Iy3FqQBfnUZR42PKQFksBr9QKVXCPusD3OiA/RkQ5kP8qV/Jl1WywAp/6+dcmPM2zL1UrUahe4JqfnWWKXIul3uUbfP8njAFLW1OFr3gdFtZ72cNH+PtQT7/brW+NXqJAHh0y9V8/U/A1U7AfwIMAD7mS3pCbuWJAAAAAElFTkSuQmCC">
      </a>
    </div>
  </body>
</html>
'

In [ ]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

          -1       1.00      0.01      0.01      1650
           0       0.67      0.83      0.74      2555
           1       0.63      0.84      0.72      3154

    accuracy                           0.65      7359
   macro avg       0.77      0.56      0.49      7359
weighted avg       0.73      0.65      0.57      7359

In [ ]:
df.to_csv('reddit_preprocessing.csv', index=False)

In [ ]:
pd.read_csv('reddit_preprocessing.csv').head()

                                       clean_comment  category
0  family mormon never tried explain still stare ...         1
1  buddhism much lot compatible christianity espe...         1
2  seriously say thing first get complex explain ...        -1
3  learned want teach different focus goal not wr...         0
4  benefit may want read living buddha living chr...         1